### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by inoryy** [Inoryy/oop-projekt#1]
## MVP
- [x] Fix `Display` class
- [x] Dynamically init `TilePane`;
- [x] `FlowPane` init in FXML
- [x] Restructure existing app (move console stuff to console package)
- [x] Connect `Display` and `TilePane`
- [x] Connect `Board` and `Display`
- [x] Fix unit tests
- [x] @mihkelvaher make pretty GUI
- [x] Implement `Board::setGrid()` (or maybe `b.getCell(1).setState(0)`)
- [x] Support window resize
- [x] About (open popup with short description)
- [x] Implement Stop (Pause) button
- [x] @inoryy refactor & clean up code
## Additional
- [x] Randomized patterns
- [x] Save to file
- [x] Load from file
- [x] Presets
- [x] Control percent of `Cell`s alive at the start (via slider)
- [x] Allow users to preset board
- [x] ~~Set rows/cols of the `Board`~~

**Comment by inoryy** [comment]
@mihkelvaher
